name: Selenium E2E test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Run Test
        run: mvn clean test